name: PR Checks
on: [pull_request]

jobs:
  run-plogon:
    name: Build Plugins
    runs-on: ubuntu-latest
    steps:
    - name: Checkout manifests
      uses: actions/checkout@v3
      with:
        repository: goatcorp/DalamudPluginsD17
        path: manifests
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout Plogon
      uses: actions/checkout@v3
      with:
        repository: goatcorp/Plogon
        #ref: V1.0.6
        path: Plogon

    - name: Create required folders
      run: |
        mkdir output
        mkdir artifacts
        mkdir static
        mkdir work

    - name: Run Plogon
      working-directory: Plogon/Plogon
      run: |
        dotnet run -- \
        --manifest-folder="${{ github.workspace }}/manifests" \
        --output-folder="${{ github.workspace }}/output" \
        --work-folder="${{ github.workspace }}/work" \
        --static-folder="${{ github.workspace }}/Plogon/Plogon/static" \
        --artifact-folder="${{ github.workspace }}/artifact" \
        --ci --actor="${{ github.event.pull_request.user.login }}"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin-artifact
        path: artifacts
